application: triangulizor
version: 1
runtime: python27
threadsafe: true
api_version: 1

builtins:
- appstats: on
- deferred: on
- remote_api: on

libraries:
- name: jinja2
  version: latest
- name: PIL
  version: latest

handlers:
- url: /(favicon\.ico|robots\.txt)
  static_files: static/\1
  upload: static/(favicon\.ico|robots\.txt)

- url: /static
  static_dir: static

- url: /.*
  script: main.app
